    export const ClavieCalcul = [
        { type: 'deleteLastOne', value: 'C',color:'orange' },
        {type: 'delete', value: 'AC' ,color:'orange' },
        {type:'per', value:'%', color:'orange'},
        { type: 'divide', value: '/', color:'orange' },
        {type: 'number', value: '7'},
        {type: 'number', value: '8'},
        {type: 'number', value: '9'},
        { type: 'multiply', value: '*' ,color:'orange' },
        {type: 'number', value: '4'},
        {type: 'number', value: '5'},
        {type: 'number', value: '6'},
        { type: 'subtract', value: '-', color:'orange'},
        {type: 'number', value: '1'},
        {type: 'number', value: '2'},
        {type: 'number', value: '3'},
        { type: 'add', value: '+', color:'orange' },
        { type: 'resize', value: 'r', color:'orange' },
        {type: 'number', value: '0'},
        { type: 'decimal', value: '.'},
        { type: 'calculate', value: '=' ,background:'orange'}, 
    ]