    export const ClavieCalculPortrait = [
        {type: 'delete', value: 'AC' ,color:'orange' },
        { type: 'deleteLastOne', value: 'C',color:'orange' },
        {type:'operation', value:'%', color:'orange'},
        { type: 'operation', value: '/', color:'orange' },
        {type: 'number', value: '7'},
        {type: 'number', value: '8'},
        {type: 'number', value: '9'},
        { type: 'operation', value: '*' ,color:'orange' },
        {type: 'number', value: '4'},
        {type: 'number', value: '5'},
        {type: 'number', value: '6'},
        { type: 'operation', value: '-', color:'orange'},
        {type: 'number', value: '1'},
        {type: 'number', value: '2'},
        {type: 'number', value: '3'},
        { type: 'operation', value: '+', color:'orange' },
        { type: 'number', value: '00'},
        {type: 'number', value: '0'},
        { type: 'decimal', value: '.'},
        { type: 'calculate', value: '=' ,background:'orange'}, 
    ]

    export const ClavieCalculLandscape = [
        {type: 'delete', value: 'AC' ,color:'orange' },
        { type: 'deleteLastOne', value: 'C',color:'orange' },
        {type:'operation', value:'%', color:'orange'},
        { type: 'operation', value: '/', color:'orange' },
        { type: 'operation', value: '*' ,color:'orange' },
        {type: 'number', value: '6'},
        {type: 'number', value: '7'},
        {type: 'number', value: '8'},
        {type: 'number', value: '9'},
        { type: 'operation', value: '-', color:'orange'},
        {type: 'number', value: '5'},
        {type: 'number', value: '4'},
        {type: 'number', value: '3'},
        {type: 'number', value: '2'},
        { type: 'operation', value: '+', color:'orange' },
        { type: 'number', value: '00'},
        {type: 'number', value: '1'},
        {type: 'number', value: '0'},
        { type: 'decimal', value: '.'},
        { type: 'calculate', value: '=' ,background:'orange'}, 
    ]